# Generated by Django 4.2.18 on 2025-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
            options={
                'verbose_name': 'Carusel of products',
                'verbose_name_plural': 'Carusel of products',
            },
        ),
    ]
