# Generated by Django 4.2.18 on 2025-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Hotdogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название продукта')),
                ('structure', models.TextField(max_length=400, verbose_name='Ингредиенты продукта')),
                ('img', models.ImageField(upload_to='static/main/img')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена продукта')),
            ],
        ),
    ]
