# Generated by Django 4.2.18 on 2025-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfasts',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
        migrations.AlterField(
            model_name='hotdogs',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='img',
            field=models.ImageField(upload_to='base_menu/static/base_menu/img'),
        ),
    ]
